### ISSUE TITLE
Object do not get default value when property do not exist in object

### ISSUE THREAD

**Issue by siyong** [immanuel192/dtobase#1]
Hi, 

I have a schema with a property with default value, but it does not get populated.

From the codes, it seems that the default value gets populated in the function **convertPrimitiveType**, however this function is not called as it is within the if block **if (fieldName in input)**, and the object do not have that property.

**Comment by immanuel192** [comment]
hi @siyong 

My changes in #3f89fd7, #0d13df7, #08d74d1 will help to solve this issue. Let's me publish the package with new version

Thanks
